apiVersion: apps/v1
kind: Service
metadata:
  name: gbook-fe-srv
  labels:
    name: gbook-fe-srv
    app: gbook-app

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    name: gbook-fe