apiVersion: v1
kind: Service
metadata:
  name: nginx-srv
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30008
      targetPort: 80


  selector:
    app: web-app
