apiVersion: v1
kind: Service
metadata:
  name: gbook-redis-srv
  labels:
    name: gbook-redis-srv
    app: gbook-app

spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-be